### ISSUE TITLE
libmysqlclient.so.20 - No such file or directory.

### ISSUE THREAD

**Issue by aardmark** [dbsanfte/eqemu-server-docker#3]
Hi,

When I try and run the login server, world server, share-memory or zones I receive the following error...

`error while loading shared libraries: libmysqlclient.so.20: cannot open shared object file: No such file or directory`

I've tried to work out what's wrong but it's beyond me I'm afraid.

Thanks,
Mark

**Comment by dbsanfte** [comment]
Correct this is broken, looking at it now

**Comment by dbsanfte** [comment]
Try the :latest tag in about an hour. Should be fixed then
